DEBUG: false
DEBUG_FREQ: 5
LOGDIR: ''
DEVICE: 'cuda'
EXP_NAME: 'tepose'
OUTPUT_DIR: 'experiments'
NUM_WORKERS: 16
SEED_VALUE: 1
DATASET:
  SEQLEN: 16
  VIDLEN: 1000
LOSS:
  KP_2D_W: 300.0
  KP_3D_W: 300.0
  SHAPE_W: 0.06
  POSE_W: 60.0
  D_MOTION_LOSS_W: 0.0
TRAIN:
  BATCH_SIZE: 32
  NUM_ITERS_PER_EPOCH: 500
  UPDATE_THETA_RATE: 1.0
  PRETRAINED: ''
  PRETRAINED_REGRESSOR: './data/base_data/spin_model_checkpoint.pth.tar'
  RESUME: ''
  START_EPOCH: 0
  END_EPOCH: 30
  LR_PATIENCE: 5
  DATA_2D_RATIO: 0.6
  DATASETS_2D:
    - 'Insta'
#    - 'PoseTrack'
#    - 'PennAction'
  DATASETS_3D:
    - 'ThreeDPW'
    - 'MPII3D'
    - 'Human36M'
  DATASET_EVAL: 'ThreeDPW' #'Human36M'
  GEN_LR: 0.00005
  GEN_WD: 0.0
  MOT_DISCR:
    OPTIM: 'Adam'
    LR: 0.0001
    WD: 0.0001
    MOMENTUM: 0.9
    GCN:
      num_class: 2
      num_point: 24
      num_person: 1
      num_gcn_scales: 13    # `num_scales` == `K + 1` in the paper
      num_g3d_scales: 6
      graph: lib.graph.smplx_theta.AdjMatrixGraph
MODEL:
  TEMPORAL_TYPE: 'gru'
  TGRU:
    NUM_LAYERS: 2
    HIDDEN_SIZE: 1024
